//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCondition) DeepCopyInto(out *ClusterCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCondition.
func (in *ClusterCondition) DeepCopy() *ClusterCondition {
	if in == nil {
		return nil
	}
	out := new(ClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentReplicaLocation) DeepCopyInto(out *CurrentReplicaLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentReplicaLocation.
func (in *CurrentReplicaLocation) DeepCopy() *CurrentReplicaLocation {
	if in == nil {
		return nil
	}
	out := new(CurrentReplicaLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalDeployment) DeepCopyInto(out *GlobalDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalDeployment.
func (in *GlobalDeployment) DeepCopy() *GlobalDeployment {
	if in == nil {
		return nil
	}
	out := new(GlobalDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalDeploymentList) DeepCopyInto(out *GlobalDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalDeploymentList.
func (in *GlobalDeploymentList) DeepCopy() *GlobalDeploymentList {
	if in == nil {
		return nil
	}
	out := new(GlobalDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalDeploymentSpec) DeepCopyInto(out *GlobalDeploymentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalDeploymentSpec.
func (in *GlobalDeploymentSpec) DeepCopy() *GlobalDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalDeploymentStatus) DeepCopyInto(out *GlobalDeploymentStatus) {
	*out = *in
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalDeploymentStatus.
func (in *GlobalDeploymentStatus) DeepCopy() *GlobalDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(GlobalDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalHumanReadableSummary) DeepCopyInto(out *GoalHumanReadableSummary) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(float64)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(float64)
		**out = **in
	}
	if in.Delta != nil {
		in, out := &in.Delta, &out.Delta
		*out = new(float64)
		**out = **in
	}
	if in.Detail != nil {
		in, out := &in.Detail, &out.Detail
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalHumanReadableSummary.
func (in *GoalHumanReadableSummary) DeepCopy() *GoalHumanReadableSummary {
	if in == nil {
		return nil
	}
	out := new(GoalHumanReadableSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalScoreSummary) DeepCopyInto(out *GoalScoreSummary) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(float64)
		**out = **in
	}
	if in.CurrentScore != nil {
		in, out := &in.CurrentScore, &out.CurrentScore
		*out = new(float64)
		**out = **in
	}
	if in.ExpectedScore != nil {
		in, out := &in.ExpectedScore, &out.ExpectedScore
		*out = new(float64)
		**out = **in
	}
	if in.EstimatedImprovementScore != nil {
		in, out := &in.EstimatedImprovementScore, &out.EstimatedImprovementScore
		*out = new(float64)
		**out = **in
	}
	if in.HumanReadable != nil {
		in, out := &in.HumanReadable, &out.HumanReadable
		*out = new(GoalHumanReadableSummary)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalScoreSummary.
func (in *GoalScoreSummary) DeepCopy() *GoalScoreSummary {
	if in == nil {
		return nil
	}
	out := new(GoalScoreSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectRef) DeepCopyInto(out *LocalObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectRef.
func (in *LocalObjectRef) DeepCopy() *LocalObjectRef {
	if in == nil {
		return nil
	}
	out := new(LocalObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveLocation) DeepCopyInto(out *MoveLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveLocation.
func (in *MoveLocation) DeepCopy() *MoveLocation {
	if in == nil {
		return nil
	}
	out := new(MoveLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveStatus) DeepCopyInto(out *MoveStatus) {
	*out = *in
	out.GlobalDeploymentRef = in.GlobalDeploymentRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveStatus.
func (in *MoveStatus) DeepCopy() *MoveStatus {
	if in == nil {
		return nil
	}
	out := new(MoveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectRef) DeepCopyInto(out *NamespacedObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectRef.
func (in *NamespacedObjectRef) DeepCopy() *NamespacedObjectRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResources) DeepCopyInto(out *NodeResources) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	out.Pods = in.Pods.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResources.
func (in *NodeResources) DeepCopy() *NodeResources {
	if in == nil {
		return nil
	}
	out := new(NodeResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSummary) DeepCopyInto(out *NodeSummary) {
	*out = *in
	in.Allocatable.DeepCopyInto(&out.Allocatable)
	in.Requested.DeepCopyInto(&out.Requested)
	in.Free.DeepCopyInto(&out.Free)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSummary.
func (in *NodeSummary) DeepCopy() *NodeSummary {
	if in == nil {
		return nil
	}
	out := new(NodeSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationGoal) DeepCopyInto(out *OptimizationGoal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationGoal.
func (in *OptimizationGoal) DeepCopy() *OptimizationGoal {
	if in == nil {
		return nil
	}
	out := new(OptimizationGoal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationPolicy) DeepCopyInto(out *OptimizationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationPolicy.
func (in *OptimizationPolicy) DeepCopy() *OptimizationPolicy {
	if in == nil {
		return nil
	}
	out := new(OptimizationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OptimizationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationPolicyList) DeepCopyInto(out *OptimizationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OptimizationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationPolicyList.
func (in *OptimizationPolicyList) DeepCopy() *OptimizationPolicyList {
	if in == nil {
		return nil
	}
	out := new(OptimizationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OptimizationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationPolicySpec) DeepCopyInto(out *OptimizationPolicySpec) {
	*out = *in
	if in.TargetSelector != nil {
		in, out := &in.TargetSelector, &out.TargetSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.OptimizationGoals != nil {
		in, out := &in.OptimizationGoals, &out.OptimizationGoals
		*out = make([]OptimizationGoal, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationPolicySpec.
func (in *OptimizationPolicySpec) DeepCopy() *OptimizationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(OptimizationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationPolicyStatus) DeepCopyInto(out *OptimizationPolicyStatus) {
	*out = *in
	if in.CurrentLayout != nil {
		in, out := &in.CurrentLayout, &out.CurrentLayout
		*out = make([]CurrentReplicaLocation, len(*in))
		copy(*out, *in)
	}
	if in.UnstableReasonsCount != nil {
		in, out := &in.UnstableReasonsCount, &out.UnstableReasonsCount
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.LastEvaluationTime.DeepCopyInto(&out.LastEvaluationTime)
	if in.LatestPlanRef != nil {
		in, out := &in.LatestPlanRef, &out.LatestPlanRef
		*out = new(LocalObjectRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationPolicyStatus.
func (in *OptimizationPolicyStatus) DeepCopy() *OptimizationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(OptimizationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanExecutionSummary) DeepCopyInto(out *PlanExecutionSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanExecutionSummary.
func (in *PlanExecutionSummary) DeepCopy() *PlanExecutionSummary {
	if in == nil {
		return nil
	}
	out := new(PlanExecutionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanMove) DeepCopyInto(out *PlanMove) {
	*out = *in
	out.GlobalDeploymentRef = in.GlobalDeploymentRef
	out.Source = in.Source
	out.Destination = in.Destination
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanMove.
func (in *PlanMove) DeepCopy() *PlanMove {
	if in == nil {
		return nil
	}
	out := new(PlanMove)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanSummary) DeepCopyInto(out *PlanSummary) {
	*out = *in
	if in.GoalScores != nil {
		in, out := &in.GoalScores, &out.GoalScores
		*out = make(map[string]GoalScoreSummary, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.EstimatedImprovementScore != nil {
		in, out := &in.EstimatedImprovementScore, &out.EstimatedImprovementScore
		*out = new(float64)
		**out = **in
	}
	if in.PodsToMove != nil {
		in, out := &in.PodsToMove, &out.PodsToMove
		*out = new(int32)
		**out = **in
	}
	if in.CurrentScore != nil {
		in, out := &in.CurrentScore, &out.CurrentScore
		*out = new(float64)
		**out = **in
	}
	if in.ExpectedScore != nil {
		in, out := &in.ExpectedScore, &out.ExpectedScore
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanSummary.
func (in *PlanSummary) DeepCopy() *PlanSummary {
	if in == nil {
		return nil
	}
	out := new(PlanSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReOrchestrationPlan) DeepCopyInto(out *ReOrchestrationPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReOrchestrationPlan.
func (in *ReOrchestrationPlan) DeepCopy() *ReOrchestrationPlan {
	if in == nil {
		return nil
	}
	out := new(ReOrchestrationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReOrchestrationPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReOrchestrationPlanList) DeepCopyInto(out *ReOrchestrationPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReOrchestrationPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReOrchestrationPlanList.
func (in *ReOrchestrationPlanList) DeepCopy() *ReOrchestrationPlanList {
	if in == nil {
		return nil
	}
	out := new(ReOrchestrationPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReOrchestrationPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReOrchestrationPlanSpec) DeepCopyInto(out *ReOrchestrationPlanSpec) {
	*out = *in
	in.Summary.DeepCopyInto(&out.Summary)
	if in.Moves != nil {
		in, out := &in.Moves, &out.Moves
		*out = make([]PlanMove, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReOrchestrationPlanSpec.
func (in *ReOrchestrationPlanSpec) DeepCopy() *ReOrchestrationPlanSpec {
	if in == nil {
		return nil
	}
	out := new(ReOrchestrationPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReOrchestrationPlanStatus) DeepCopyInto(out *ReOrchestrationPlanStatus) {
	*out = *in
	out.Summary = in.Summary
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.CompletionTime.DeepCopyInto(&out.CompletionTime)
	if in.MoveStatuses != nil {
		in, out := &in.MoveStatuses, &out.MoveStatuses
		*out = make([]MoveStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReOrchestrationPlanStatus.
func (in *ReOrchestrationPlanStatus) DeepCopy() *ReOrchestrationPlanStatus {
	if in == nil {
		return nil
	}
	out := new(ReOrchestrationPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaBinding) DeepCopyInto(out *ReplicaBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaBinding.
func (in *ReplicaBinding) DeepCopy() *ReplicaBinding {
	if in == nil {
		return nil
	}
	out := new(ReplicaBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicaBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaBindingList) DeepCopyInto(out *ReplicaBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReplicaBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaBindingList.
func (in *ReplicaBindingList) DeepCopy() *ReplicaBindingList {
	if in == nil {
		return nil
	}
	out := new(ReplicaBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicaBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaBindingRescheduleStatus) DeepCopyInto(out *ReplicaBindingRescheduleStatus) {
	*out = *in
	in.LastHandledTime.DeepCopyInto(&out.LastHandledTime)
	out.ObservedLocation = in.ObservedLocation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaBindingRescheduleStatus.
func (in *ReplicaBindingRescheduleStatus) DeepCopy() *ReplicaBindingRescheduleStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaBindingRescheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaBindingSpec) DeepCopyInto(out *ReplicaBindingSpec) {
	*out = *in
	out.GlobalDeploymentRef = in.GlobalDeploymentRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaBindingSpec.
func (in *ReplicaBindingSpec) DeepCopy() *ReplicaBindingSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicaBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaBindingStatus) DeepCopyInto(out *ReplicaBindingStatus) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.Reschedule.DeepCopyInto(&out.Reschedule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaBindingStatus.
func (in *ReplicaBindingStatus) DeepCopy() *ReplicaBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RescheduleObservedLocation) DeepCopyInto(out *RescheduleObservedLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RescheduleObservedLocation.
func (in *RescheduleObservedLocation) DeepCopy() *RescheduleObservedLocation {
	if in == nil {
		return nil
	}
	out := new(RescheduleObservedLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceList) DeepCopyInto(out *ResourceList) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceList.
func (in *ResourceList) DeepCopy() *ResourceList {
	if in == nil {
		return nil
	}
	out := new(ResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	in.Capacity.DeepCopyInto(&out.Capacity)
	in.Allocatable.DeepCopyInto(&out.Allocatable)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}
